### PR TITLE
Support latest minestom

### PR DESCRIPTION
**Pull request by mani1232**

### CODE REVIEW

**Review by Shynixn — CHANGES_REQUESTED** [review]
Thanks for the contribution but I want to keep supporting Java 8.Your changes would break support for it. So i will not merge it.

If you change your PR to only modify the minestom modules and not touch the Kotlin versions, I can approve it.

**Comment by mani1232** [comment]
> Thanks for the contribution but I want to keep supporting Java 8.Your changes would break support for it. So i will not merge it.
> 
> If you change your PR to only modify the minestom modules and not touch the Kotlin versions, I can approve it.

Folia and minestom required java 21 (for 1.21)

**Comment by mani1232** [comment]
Execution failed for task ':mccoroutine-bukkit-api:compileKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileJava' (21) and 'compileKotlin' (1.8).

minecraft 1.21+ required java 21

**Review by Shynixn — CHANGES_REQUESTED** [review]
* What's ``dev.hollowcube:minestom-ce-extensions:1.2.0`` ?
* Do not use relase candidate versions (e.g. 2.0.10-RC)
* Do only modify the minestom modules. The other modules have been modified (e.g. Folia changes are simply wrong)

I'll start reviewing the individual changes, once these have been resolved.

**Comment by mani1232** [comment]
> * What's `dev.hollowcube:minestom-ce-extensions:1.2.0` ?
> * Do not use relase candidate versions (e.g. 2.0.10-RC)
> * Do only modify the minestom modules. The other modules have been modified (e.g. Folia changes are not correct)
> 
> I'll start reviewing the individual changes, once these have been resolved.

1. Minestom remove extensions, https://github.com/Minestom/Minestom/commit/e1140b58563c841a970a59731b0f5d2f2e7da027

2. 2.0.X contains fixes from 2.0.0 release, im can set it to 2.0.0 if you want

3. Changed only gradle scripts. What exactly is wrong with it?

**Comment by mani1232** [comment]
Temp repo

```kotlin
maven {
    url = uri("https://repo.worldmandia.cc/releases")
}
```

```kotlin
implementation("com.github.shynixn.mccoroutine:mccoroutine-minestom-core:2.18.1")
```

**Comment by Shynixn** [comment]
I'll review and merge your PR once i have got time.

**Comment by Shynixn** [comment]
Thank you for your contribution. Looks (mostly) fine. 👍

**Pull request merged**
