### PR TITLE
Fix async coroutine exception event and gitignore

### PR DESCRIPTION
**Pull request by Spliterash**
When plugin use asyncEventDispatcher in coroutines, and inside coroutines drop exception, bukkit crash, because exception throws not in main thread
image

### CODE REVIEW

**Comment by Shynixn** [comment]
Hello, thank you for reporting and fixing this. This problem was probably introduced in 2.6.0 by moving from standard event to plugin event. It may even be better to revert the 2.6.0 change in MCCoroutine. However, I may need some days until I can work on it.

**Comment by Spliterash** [comment]
@Shynixn No it's not that.  It's just that bukkit requires you to explicitly specify what type of event (synchronous or asynchronous), and PluginEvent does not have the right constructor where you can pass this parameter

**Comment by Shynixn** [comment]
I see but there may be more to that. The MCCoroutine docs explicitly state how the MCCoroutineException event is always going to arrive on the primary thread. https://shynixn.github.io/MCCoroutine/wiki/site/exception/
That's the way I have designed it and according to your error something is not right. 

Can you please send a short code snippet to trigger that error?

**Comment by Spliterash** [comment]
```kotlin
plugin.scope.launch(asyncDispatcher) {
    throw RuntimeException("Exception in async dispatcher")
}
```

**Comment by Shynixn** [comment]
I have done some testing:
* It is actually a bug caused by Paper. It works when using spigot.
* I'll merge your pull request but change a little bit. 

Thanks for your help.

**Review by Shynixn — APPROVED** [review]

**Pull request merged**
